# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wlIsA08MddeqI_W83sYJOxDDjlbaeOVl
"""

!pip install pyshorteners

import pyshorteners

def shorten_url(url):
    # Create a Shortener object
    shortener = pyshorteners.Shortener()

    # Shorten the URL
    shortened_url = shortener.tinyurl.short(url)

    return shortened_url

# Example usage
long_url = "https://www.reuters.com/article/urnidgns002570f3005978d8002576f60035a6bb-idUS98192761820100330"
short_url = shorten_url(long_url)
print("Shortened URL:", short_url)